### PR TITLE
Setup/app skeleton

### PR DESCRIPTION
**Pull request by lily-law**
I've changed Widget to accept a type prop instead of Sticky injecting itself into a Widget to make things clearer.
All writable (and subscribe-able) store references are now named with an _
Will write up a short bullet point soon

### CODE REVIEW

**Comment by lily-law** [comment]
This seems to now be working fine, I've put in enough of a basic setup for the dataStore.js so everyone can get started on any features that need it. 
yanpelov dataStore still needs more functions (delete widget, delete dash... also a way to pack and unpack the stores into JSON) and I doubt whats there is perfect. I did see [svelte crud example](https://svelte.dev/examples#7guis-crud) which might give some ideas for other ways about it.

- any store references now have a _ at the start so this should help keep track of whats a reference/object with update(bind)/subscribe($) methods.

### overview
- App
    - components/DashNav
    - components/Dash
        - components/widgets/Widget
            - components/widgets/Sticky
                - utils/detectInputType
                - components/widgets/stickyTypes/Text
    - components/WidgetMenu
        - components/buttons/Add
        - components/buttons/Trash
- dataStore

**Comment by yanpelov** [comment]
Hi, I would suggest a little bit more informative commits. for example, if an update in a x module was made, it would be nice if the title could describe the update and if needed extra information would be added to the body of the commit. 
Here is a great source:
https://chris.beams.io/posts/git-commit/

If it's okay by you, you can amend previous commits (edit only their messages) without changing their contents.

Also, you can git squash together (combine) a few commits together that have something in common and make 1 commit out of them.

**Comment by lily-law** [comment]
Cool I'll have a go at that thanks

**Comment by zsigil** [comment]
WE DID IT!

**Pull request merged**
